server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      
      - source_labels: ['__meta_docker_container_label_app']
        target_label: 'app'
      
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service'
      
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/*.log'