name: Docker Compose Up

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Run Docker Compose
        run: docker compose up -d
      
      - name: Wait for services to be ready
        run: sleep 120
      
      - name: Check running containers
        run: docker compose ps
      
      - name: Ping Python Service
        run: curl -f http://localhost:5000/ || exit 1